---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./vizag/dell/cu

# Apps of Apps
resources:

  # - 10-gemini.yaml
  - 10-dev-cluster.yaml
  - 20-dev-cluster-sriovconfig.yaml
  - 30-dev-cluster-ptpconfig.yaml