apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 09_node_autolabeler_policy.yaml
  - 10_node_autolabeler_placementbinding.yaml
  - 11_node_autolabeler_placementrule.yaml
